# Base configs
# baseurl: "https://photounion.github.io/portfolio"
baseurl: "https://photounion.github.io/portfolio"
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: "UA-152728130-1"

# UI configs
title: "@photo_union_kzn"
header:
 title: "@photo_union_kzn"
 subtitle: "portfolio"
 about_ph: "О фотографе | Цены"
social_urls:
  instagram: "https://www.instagram.com/photo_union_kzn"
