# Base configs
# baseurl: "https://photounion.github.io/portfolio"
baseurl: "portfolio"
image_fulls_loc: "images/fulls"
image_thumbs_loc: "images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "@photo_union_kzn"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "@photo_union_kzn"
 subtitle: "portfolio"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/photo_union_kzn"
